### ISSUE TITLE
retry connecting to hub in case it hasn't started yet

### ISSUE THREAD

**Issue by jedwards1211** [AkeemMcLennon/docker-selenium-node-phantomjs#6]
I tried using this with docker compose, but it fails to launch because the selenium-hub hasn't finished starting up by the time it runs.

https://docs.docker.com/compose/startup-order/ states:

> Compose will not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running. There’s a good reason for this.
> 
> The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.
> 
> To handle this, your application should attempt to re-establish a connection to the database after a failure. If the application retries the connection, it should eventually be able to connect to the database.

So the best solution to this problem is to make this container keep trying to connect to the selenium hub.

**Comment by AkeemMcLennon** [comment]
Fixed by #7
